apiVersion: v1
kind: ImageStream
metadata:
  labels:
    role: jenkins-slave
  name: rust
spec:
  tags:
  - from:
      kind: DockerImage
      name: docker.io/outtherelabs/jenkins-slave-rust:v1.26.0
    name: latest
